import easyocr
import pyttsx3
reader = easyocr.Reader(['en'],gpu=False)
result = reader.readtext('../Desktop/Capture.PNG',detail = 0)
print(result)
engine = pyttsx3.init()
rate = engine.getProperty('rate')   
engine.setProperty('rate', 125)
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)
i=" ".join(result)
engine.say(i)
engine.runAndWait()
reader = easyocr.Reader(['en'],gpu=False)
result = reader.readtext('../Desktop/Capture1.PNG',detail = 0)
print(result)
engine = pyttsx3.init()
rate = engine.getProperty('rate')   
engine.setProperty('rate', 150)
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)
i=" ".join(result)
engine.say(i)
engine.runAndWait()
